name: PlayerTop
main: cn.handyplus.top.PlayerTop
version: 1.4.4
author: handy
website: https://ricedoc.handyplus.cn/wiki/PlayerTop/log
api-version: 1.13
softdepend: [ PlaceholderAPI,Vault,PlayerPoints,PlayerTitle,PlayerTask,PlayerGuild,HolographicDisplays,mcMMO,CMI,Jobs,Multiverse-Core,lris,DecentHolograms ]
description: 玩家排行
folia-supported: true
commands:
  playerTop:
    description: 玩家排行
    aliases: [ pt ]
permissions:
  playerTop.*:
    description: 玩家排行插件
    children:
      playerTop.reload: true
      playerTop.createHd: true
      playerTop.init: true
      playerTop.delete: true
      playerTop.moveHd: true
  playerTop.reload:
    description: 重新加载配置
    default: op
  playerTop.createHd:
    description: 创建全息图
    default: op
  playerTop.init:
    description: 初始化数据
    default: op
  playerTop.delete:
    description: 删除数据
    default: op
  playerTop.moveHd:
    description: 移动位置
    default: op